# Generated by Django 4.1.7 on 2023-07-03 01:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oco_nomeOcorrencia', models.CharField(max_length=120)),
                ('oco_dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('oco_dataAlteracao', models.DateTimeField(auto_now=True)),
                ('oco_descricaoOcorrencia', models.CharField(max_length=120)),
                ('oco_ipAddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc_tipoOcorrencia', models.CharField(max_length=50)),
                ('toc_dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('toc_dataAlteracao', models.DateTimeField(auto_now=True)),
                ('toc_ipAddress', models.GenericIPAddressField()),
                ('toc_usuario', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_dataRegistro', models.DateTimeField(auto_now=True)),
                ('reg_dataOcorrencia', models.DateTimeField(auto_now=True)),
                ('reg_descricaoRegistro', models.TextField(max_length=500)),
                ('reg_localOcorrencia', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('reg_ipAddress', models.GenericIPAddressField()),
                ('reg_Ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebGis.ocorrencia')),
                ('reg_usuarioRegistro', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='oco_tipoOcorrencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebGis.tipoocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='oco_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
