# Generated by Django 4.1.7 on 2023-06-26 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oco_nomeOcorrencia', models.CharField(max_length=120)),
                ('oco_dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('oco_dataAlteracao', models.DateTimeField(auto_now=True)),
                ('oco_descricaoOcorrencia', models.CharField(max_length=120)),
                ('oco_ipAddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc_tipoOcorrencia', models.CharField(max_length=50)),
                ('toc_dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('toc_dataAlteracao', models.DateTimeField(auto_now=True)),
                ('toc_ipAddress', models.GenericIPAddressField()),
                ('toc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
