# Generated by Django 4.1.9 on 2023-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0002_remove_registroocorrencia_reg_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroservico',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descreva sucintamente a sua demanda/ocorrência (até 500 caracteres)', max_length=500, null=True, verbose_name='Descreve a ocorrência'),
        ),
    ]
