# Generated by Django 4.1.7 on 2023-07-04 15:33

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebGis', '0002_alter_ocorrencia_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='oco_status',
            field=models.BooleanField(default=True, help_text='Indica se o serviço está ativo ou não', verbose_name='Status do Serviço'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_dataAlteracao',
            field=models.DateTimeField(auto_now=True, help_text='Data em que foi alterado o cadastro do serviço', verbose_name='Data da Alteração'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_dataCadastro',
            field=models.DateTimeField(auto_now_add=True, help_text='Data do cadastro de determinado serviço', verbose_name='Data do Cadastro'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_descricaoOcorrencia',
            field=models.CharField(help_text='Descreva de forma clara e sucinta o serviço.', max_length=120, verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_ipAddress',
            field=models.GenericIPAddressField(help_text='Endereço IP do usuário que efetuou cadastro ou a última alteração', verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_nomeOcorrencia',
            field=models.CharField(db_index=True, help_text='Nome que identifica uma situação que será registrada', max_length=120, unique=True, verbose_name='Nome do Serviço'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_tipoOcorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebGis.tipoocorrencia'),
        ),
        migrations.RemoveField(
            model_name='registroocorrencia',
            name='reg_Ocorrencia',
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_dataOcorrencia',
            field=models.DateTimeField(auto_now_add=True, help_text='Data efetiva da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_dataRegistro',
            field=models.DateTimeField(auto_now=True, help_text='Data de Registro da Ocorrência', verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_descricaoRegistro',
            field=models.TextField(help_text='Descreva clara e sucintamente seu Reporte', max_length=500, verbose_name='Descrição do Registro'),
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_ipAddress',
            field=models.GenericIPAddressField(help_text='Endereço IP', verbose_name='Endereço IP do Usuário'),
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_localOcorrencia',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas Geográficas do local onde ocorreu seu Reporte', srid=4326, verbose_name='Coordenadas do Local'),
        ),
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_usuarioRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_dataAlteracao',
            field=models.DateTimeField(auto_now=True, help_text='Data em que ocorreu a última alteração da Categoria', verbose_name='Data da Alteração'),
        ),
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_dataCadastro',
            field=models.DateTimeField(auto_now_add=True, help_text='Data na qual houve o Cadastro da Categoria', verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_ipAddress',
            field=models.GenericIPAddressField(help_text='Endereço IP do Usuário que efetuou o Cadastro ou Alteração', verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_tipoOcorrencia',
            field=models.CharField(db_index=True, help_text='Categoria na qual o Reporte será classificado', max_length=50, unique=True, verbose_name='Categoria do Reporte'),
        ),
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroocorrencia',
            name='reg_Ocorrencia',
            field=models.ManyToManyField(to='WebGis.ocorrencia'),
        ),
    ]
