# Generated by Django 4.1.7 on 2023-07-04 18:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0003_ocorrencia_oco_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocorrencia',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='registroocorrencia',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tipoocorrencia',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
