# Generated by Django 4.1.7 on 2023-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0005_tipoocorrencia_toc_descocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoocorrencia',
            name='toc_descOcorrencia',
            field=models.CharField(help_text='Descrição sucinta da Categoria', max_length=250, verbose_name='Descrição da Categoria'),
        ),
    ]
