# Generated by Django 4.1.9 on 2023-07-09 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebGis', '0005_alter_campus_ponto_central'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', help_text='Informe com qual Gênero você se Identifica.', max_length=2, verbose_name='Gênero d(ao) Usuári(ao)')),
                ('aniversario', models.DateField(blank=True, help_text='Informe a Data do Seu Aniversário', verbose_name='Data de Aniversario do Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ug', models.CharField(help_text='Informe o Nome da Unidade Gestora', max_length=60, verbose_name='Nome da Unidade Gestora')),
                ('descricao', models.TextField(blank=True, help_text='Descreva sucintamente a respeitor desta Unidade Gestora', max_length=200, null=True, verbose_name='Descrição da Unidade Gestora')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebGis.reporteusuario', verbose_name='usuarios_reporte')),
            ],
        ),
    ]
