# Generated by Django 4.1.7 on 2023-07-04 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebGis', '0006_alter_tipoocorrencia_toc_descocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_tipoOcorrencia',
            field=models.ForeignKey(help_text='Nome da Categoria que o Serviço se enquadra', on_delete=django.db.models.deletion.CASCADE, to='WebGis.tipoocorrencia', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='oco_usuario',
            field=models.ForeignKey(help_text='Usuário que cadastrou ou alterou um Serviço', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
