# Generated by Django 4.1.9 on 2023-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0006_reporteusuario_unidadegestora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroservico',
            name='foto',
            field=models.FileField(blank=True, help_text='Foto da Ocorrência', null=True, upload_to='fotos/', verbose_name='Permite a inserção de uma Foto para Registro da Ocorrência'),
        ),
    ]
