# Generated by Django 4.1.7 on 2023-07-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0007_alter_ocorrencia_oco_tipoocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroocorrencia',
            name='reg_Ocorrencia',
            field=models.ManyToManyField(help_text='Relação com a Tabela de Serviços', to='WebGis.ocorrencia', verbose_name='Código do Serviço'),
        ),
    ]
