# Generated by Django 4.1.7 on 2023-07-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebGis', '0008_alter_registroocorrencia_reg_ocorrencia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocorrencia',
            managers=[
            ],
        ),
    ]
